schema_version = "1.0.0"

id = "bone_widget"
version = "2.3.3"
name = "Bone Widget"
tagline = "Easily Create Bone Widgets"
maintainer = "Wayne Dixon <waylowinternet@gmail.com>"

type = "add-on"

website = "https://github.com/waylow/boneWidget"

tags = ["Rigging"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

[permissions]
files = "Import/export json and image files from/to disk"

[build]
paths_exclude_pattern = [
  "/.git/",
  "__pycache__/",
  "images/",
  ".*",
  "*.blend",
  "*.blend[0123456789]",
  "*.md",
  "*.zip",
]
